In [48]:
import pandas as pd
import numpy as np
import datetime as dt


def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + dt.timedelta(n)

dates = [dtt.strftime('%Y-%m-%d') for dtt in daterange(dt.datetime.strptime(f"{dt.datetime.now().year-2}-01-01", "%Y-%m-%d"),
                                                                                             dt.datetime.strptime("2025-09-30", "%Y-%m-%d"))]

kommen = [dt.datetime.strptime('08:00', '%H:%M') for i in range(len(dates))]
pause = [dt.datetime.strptime('0:30', '%H:%M') for i in range(len(dates))]
gehen = [dt.datetime.strptime('16:30', '%H:%M') if i % 3 != 0 else dt.datetime.strptime('15:30', '%H:%M') for i in range(len(dates))]   

weekday = [dt.datetime.strptime(date, '%Y-%m-%d').weekday() for date in dates]
dict_wochentag = {0:'Montag', 1:'Dienstag', 2:'Mittwoch', 3:'Donnerstag', 4:'Freitag', 5:'Samstag', 6:'Sonntag'}
wochentag = [dict_wochentag[i] for i in weekday]

dict_data = {'Datum':dates, 'Kommen':kommen, 'Pause':pause, 'Gehen':gehen}


df = pd.DataFrame(dict_data)
df['Wochentag'] = wochentag
df

,Datum,Kommen,Pause,Gehen,Wochentag
0,2020-01-01,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 15:30:00,Mittwoch
1,2020-01-02,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Donnerstag
2,2020-01-03,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Freitag
3,2020-01-04,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 15:30:00,Samstag
4,2020-01-05,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Sonntag
...,...,...,...,...,...
2095,2025-09-26,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Freitag
2096,2025-09-27,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Samstag
2097,2025-09-28,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 15:30:00,Sonntag
2098,2025-09-29,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Montag
2099,2025-09-30,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Dienstag

In [45]:
df['Summe'] = pd.to_timedelta(df.Gehen.strftime('%H:%M')) - pd.to_timedelta(df.Kommen.dt.strftime('%H:%M')) - pd.to_timedelta(df.Pause.dt.strftime('%H:%M'))

AttributeError: 'Series' object has no attribute 'strftime'

In [51]:
df.dtypes

Datum        datetime64[ns]
Kommen       datetime64[ns]
Pause        datetime64[ns]
Gehen        datetime64[ns]
Wochentag            object
dtype: object

In [52]:
df['Datum'] = pd.to_datetime(df['Datum'])

In [54]:
df.dtypes

Datum        datetime64[ns]
Kommen       datetime64[ns]
Pause        datetime64[ns]
Gehen        datetime64[ns]
Wochentag            object
dtype: object

In [56]:
kommen = ['08:00' for i in range(len(dates))]
pause = ['0:30' for i in range(len(dates))]
gehen = ['16:30' if i % 3 != 0 else '15:30' for i in range(len(dates))]

In [60]:
df = df[df['Wochentag'] != 'Samstag']
df = df[df['Wochentag'] != 'Sonntag']
df

,Datum,Kommen,Pause,Gehen,Wochentag
0,2020-01-01,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 15:30:00,Mittwoch
1,2020-01-02,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Donnerstag
2,2020-01-03,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Freitag
5,2020-01-06,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Montag
6,2020-01-07,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 15:30:00,Dienstag
...,...,...,...,...,...
2093,2025-09-24,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Mittwoch
2094,2025-09-25,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 15:30:00,Donnerstag
2095,2025-09-26,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Freitag
2098,2025-09-29,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Montag
2099,2025-09-30,1900-01-01 08:00:00,1900-01-01 00:30:00,1900-01-01 16:30:00,Dienstag